language: node_js
node_js: node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
script:
- npm run build:server:production
- npm run build:client:production
- npm test
deploy:
  provider: heroku
  api_key:
    secure: PtU+dHPCCifsOpqFH+VBUuv2yhy1cVVSMRRBpnbrdypzNcq1bf5mPqyj3quVfBuMoKJXv0TZiGNz07LwdClfnaUNQn0R5artYN290/f8nthxVJdOOmVPFx1zgFmO3gQCbUdJ5DUX6H5Zq+BvPC9dx9ZEcIZkHQeh1q4XN2GV9MskY64zPKEggRxUkm+TOa28VxzgIoZaZO+IR64tCq8Fc6vU86h8BH8Gupx6D/HlQYEJuTe+ZrGfmZFvBPJI3ZVfSgAz5gQUrB6HN8Te+n65e7wdd7O/KDD7WPpndzmNDn8JifMCy6Zkg2kHHxH2yaj65H1pYCDVWb2bPRFrHlokiH1Id4b45wzATFC4MapaQCbzgxcILj4vB8t9j3SEJ94BO6QQ/cRU9vCtnegEbUs9NYnC2O7ps5LzGRetL2HQTTg9jpSqRS5DUqnNeCEOE9z2WOZTSWAQjtSjnmsvzSNa49UOlp7txtWOUMSS9yzGZxO0kKUU4zLEx4PtB4fawmZ1OeOaayoWJC0q8mfTKxlfGnAwqbK0Ll0xLC98QUeoPAeB7602k2RbfcjH5AT2YVoHypuxd5DbMaA9cpHXVwOw2gNJ+9NhtZbyp00mBRBDUYbdGsUGlNat5vgMJEMI9s16U1T6a+O1bEd5xS9qjo9Y/2tF6ZDqMqn7+brGmf4MPqk=
  app: bingeomatic
  on:
    repo: TheresaWilkin/binge-o-matic
